### ISSUE TITLE
Contributing to Open Source

### ISSUE THREAD

**Issue by moimikey** [beerjs/nyc#6]
Hi all,

Since I'm not the biggest fan of blog writing because I can't ever finish writing something, I wanted to use the issues area here at BeerJS NYC to continue creating some topics of discussion.

I think contributions to open source is strongly encouraged here (we're on GitHub aren't we?). Personally, I've always had some trouble on contributing to open source projects on GitHub, for whatever reason(s), to which may or may not include:
- How do I find something to contribute to?
- I found something, but there isn't really much for me to contribute.
- Should I start my own project?

There's easy answers for each of these things:
- How do I find something to contribute to?
  
  > In my opinion, the best way to find something to contribute to, is not to arbitrarily pick a project, but to contribute to something that you actually use. Is there a library that you've used that you'd love to add on to? Or even help fix bugs that have haunted you during work time? Maybe even an up-and-coming or "just started" project that could use some help. It's great to start small.
- I found something, but there isn't really much for me to contribute.
  
  > It's totally okay! Be a watcher. Star the repository. Use the tool or library and see if perhaps something could be improved upon or even removed. Open up an issue. Start a discussion. I will say, some repositories/projects will have strict guidelines for how to contribute, so be sure to read those. You may be enticed to join a group mailing list. Be on the look out for specific issue labels that denote help is needed. Run their tests to see if something fails and report it. 
- Should I start my own project?
  
  > "Reinventing the wheel" is a phrase you'll hear a lot to _NOT_ do. You don't want to reinvent the wheel, but you can _improve_ the wheel. Fork a project and build upon it. Contribute to a project that could become much better. Sometimes however, you might want to go a different route. Perhaps the best project out there is too much for your needs. You want a condensed version. A smaller footprint. Perhaps a brilliant idea that currently doesn't have a project made for it, or in the language that you'd prefer. Start a project! Make a node module. Contribute to `npmjs.org`. Tag your releases. Think small. If you're into writing node modules, create one for a single isolated purpose. Take some hints from some popular contributors on NPM. You'll be surprised at how intuitive it is to bring various isolated modules in to create a new and interesting thing.

How about a Q&A? Let's discuss. We can even save it for our next beer meet!

**Comment by alexburgos** [comment]
Bravo, thanks for the tips @moimikey. I've been thinking of ways to start contributing to projects I love. I started with Yeoman and built a small generator recently.

**Comment by jdaudier** [comment]
@moimikey Do you know how to create a private module on npm?

**Comment by moimikey** [comment]
@jdaudier you can set `private: true` in your `package.json` and `npm publish ./` i think.

**Comment by jdaudier** [comment]
@moimikey thanks!

**Comment by moimikey** [comment]
a new thing that I recently open sourced as a small project to see if I could get surge pricing details for Uber from my terminal. it uses a combination of geo location via your wireless connection for lat/lng coordinates, which is then passed to Uber's API. 

https://www.npmjs.com/package/surger

```
$ npm -g install surger
$ surger

Location:  Nearby East 2nd Street

uberX       ✔ GOOD
uberXL      ✔ GOOD
UberBLACK   $ SURGE 2.8x
UberSUV     $ SURGE 2.8x
uberT       ✔ GOOD
```

**Comment by moimikey** [comment]
Hi all,

Here are some of the latest projects that could use some PRs, contributors, etc. I also have a couple of projects that I could use some extra hands with, that are React specific:
- https://github.com/moimikey/node-xero (node.js SDK for Xero)
- https://github.com/moimikey/shitty-uber (my surger project)
- https://github.com/moimikey/craic (multi-threaded node.js SSH cracker)
- https://github.com/moimikey/iso3166-1 (iso3166-1 conversion library)

I have a private repo for a side project I'm working on, called Subsy, which is a web application interface to YouTube subscriptions.

**Comment by alwinmark** [comment]
Hey guys,
I just stumbled around to find out, what beer.js is and this was the first community with a language I understand^^.

So while reading this I have the strong need to add my two cents.

`Should I start my own project?`
I would say totally yes if you have the time. First of all start does not mean finish and learning by doing is a great thing. Also it makes sense to scan github for similar projects you can lean on or to find the weak points.
But... if you want to start your own project because you want to build a community around it, you want other people to use it or you need it by yourself, I would strongly recommending to use an existing project and extend it to fit your needs and try to push your changes back. Therefore its highly important to talk to the Maintainer(s) before starting these extensions to be sure your changes will be accepted.

Also many Projects have a Plugin ability. So in these cases it makes even more often sense, to use an existing project to build up on.

What I don't recommend is forking some project without the will to merge your changes back or without talking to the maintainers. Thats just waste, as you'll most probably have to fix bugs of the original project by yourself when you've gone to far into a different direction. This is a hard lesson companies at least in germany had to take. 
Open Source Code is not your code because you've forked it. In a longterm perspective it has the same disadvantages as closed source, when you don't join the community.

**Comment by moimikey** [comment]
glad to hear @alwinmark :smile: , totally agree with your points. thanks for the 2 cents :+1:

**Comment by ionox0** [comment]
+1!
